version: '2'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3309:3306"
    env_file: .env
    restart: always

  nginx:
    image: nginx:1.9.8
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/etc/conf.d:/etc/nginx/conf.d
      - ./www:/usr/share/nginx/html
    links:
      - php-fpm
      - phpmyadmin
    restart: always

  php-fpm:
    image: php:5.6-fpm
    container_name: php-fpm
    volumes:
      - ./php/etc:/usr/local/etc/php
      - ./www:/usr/share/nginx/html
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    env_file: .env
    links:
      - mysql:db
    ports:
      - "8888:80"
    restart: always

  ghost:
    image: ghost:0.7.2
    container_name: ghost
    volumes:
      - ./ghost:/var/lib/ghost
    ports:
      - "2368:2368"
    restart: always

