version: '2'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3309:3306"
    env_file: .env
    restart: always

  nginx:
    image: nginx:1.9.8
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/etc/conf.d:/etc/nginx/conf.d
      - ./www:/usr/share/nginx/html
    links:
      - php-fpm
      - phpmyadmin
      - php-good-practice 
      - ghost 
    restart: always

  php-fpm:
    #image: php:5.6-fpm
    build: ./php 
    container_name: php-fpm
    volumes:
      - ./www:/usr/share/nginx/html
    links:
      - "mysql"
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    env_file: .env
    links:
      - mysql:db
    ports:
      - "8888:80"
    restart: always

  ghost:
    image: ghost:0.7.2
    container_name: ghost
    volumes:
      - ./ghost:/var/lib/ghost
    ports:
      - "2368:2368"
    command: npm start --production
    restart: always

  php-good-practice:
    image: dordoka/reveal
    container_name: php-good-practice
    volumes:
      - ./reveal/php-good-practice:/home/reveal/presos
    ports:
      - "8000:8000"
    restart: always

